# Generated by Django 5.0.1 on 2024-03-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chutti", "0002_leave_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="leave_hours",
        ),
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.IntegerField(
                choices=[
                    ("Full Leave", "Full Leave"),
                    ("Partial Leave", "Partial Leave"),
                ],
                default=8,
            ),
        ),
        migrations.AlterField(
            model_name="leavesleft",
            name="year",
            field=models.IntegerField(default=2024),
        ),
    ]
