# Generated by Django 5.0.1 on 2024-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chutti", "0003_remove_leave_leave_hours_leave_leave_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.TextField(
                choices=[
                    ("Full Leave", "Full Leave"),
                    ("Partial Leave", "Partial Leave"),
                ],
                default=8,
            ),
        ),
    ]
